# SPDX-FileCopyrightText: 2023 Leiden University Libraries <beheer@library.leidenuniv.nl>
#
# SPDX-License-Identifier: GPL-3.0-or-later
name: License check

on:
  pull_request_target:
    branches:
      - main

permissions:
  contents: read
  statuses: write

jobs:
  reuse:
    name: Check REUSE compliance
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v2
